# Generated by Django 2.0.7 on 2019-04-16 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isle', '0044_auto_20190313_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasbinModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CasbinPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.TextField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isle.CasbinModel')),
            ],
        ),
    ]
